steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/dft-cdg-sb-jmurray3/malware-scanner:latest' #insert project id
      - '.'
    
  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/dft-cdg-sb-jmurray3/malware-scanner:latest' #insert project id
    
  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'malware-scanner'
      - '--image'
      - 'gcr.io/dft-cdg-sb-jmurray3/malware-scanner:latest' #insert project id
      - '--region'
      - 'europe-west1' 
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '20'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '5'
      - '--no-allow-unauthenticated'
      - '--service-account'
      - 'malware-scanner@dft-cdg-sb-jmurray3.iam.gserviceaccount.com' #insert service account
